### ISSUE TITLE
באג נדיר

### ISSUE THREAD

**Issue by avraham-shmueli** [tzukpolinsky/Cardioception_ecg#1]
![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/146067695/76549e8d-5402-45b2-96d3-46bbe893382f)

**Comment by tzukpolinsky** [comment]
i think i solved it [cdfdbf6647803c7ad01651f0b334cc1bbee2715d](in this commit), i just cant reproduce it in my env

**Comment by tzukpolinsky** [comment]
sry but i cant reproduce it, probably it's in the device or the computer, we will solve this manually on your computer
