### ISSUE TITLE
keyboard only TRUE respond

### ISSUE THREAD

**Issue by avraham-shmueli** [tzukpolinsky/Cardioception_ecg#2]
כמשתמשים בkeyboard, התוכנה לא מחשבת האם התשובה נכונה או לא.
ככה שהפסיכופיזיקה לא עובדת + נשמרת תוצאה שגויה בresults.
בתמונה 1: איפה שכתוב None צריך להיות כתוב True/False
בתמונה 2: התור Respond correct ריק כאשר המטלה מתבצעת ב-keyboard. יש רק בטבלה הימנית-למעלה, שהוקלטה עם עכבר.

![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/146067695/3f2ecd93-334a-46db-971b-7285cfb7f964)
 
![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/146067695/526f6e5f-ac1b-42dd-9bcf-db49b61722cf)

**Comment by tzukpolinsky** [comment]
I think i solved it in [5af8c30973e37de1711a849b20231777535c829b](this commit) let me know

**Comment by avraham-shmueli** [comment]
Hi, the problem remained the same.

**Comment by tzukpolinsky** [comment]
i think i solved it
![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/37898801/41f2a396-49f1-491d-9f79-75207ddaf1ed)
it looks like i have almost only True because i cheated and looked at the real answers

please recheck and close
