### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by avraham-shmueli** [tzukpolinsky/Cardioception_ecg#3]
This bug occurs in the tutorial every time before slide two should be present, Thus is stuck at slide number one:

![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/146067695/fbd788cf-65c4-4d1b-bde5-04ad494c926b)

Thanks :)

**Comment by tzukpolinsky** [comment]
it's because it is not exists in the hebrew function in languages
![image](https://github.com/tzukpolinsky/Cardioception_ecg/assets/37898801/aacb5ef7-5c95-4181-a3df-055f3203a03f)

**Comment by tzukpolinsky** [comment]
move the pulse tutorial to a function that is called only if oximeter is the selected device

please check it's working and close:)
