### ISSUE TITLE
fixing tutorial progress bar slider

### ISSUE THREAD

**Issue by tzukpolinsky** [tzukpolinsky/Cardioception_ecg#5]
@avraham-shmueli
the page that display the progress bar is continue without user instructions

**Comment by tzukpolinsky** [comment]
@avraham-shmueli 
fixed in 966ed3b05b31d851f80f7daad6c00ea5ab7eb105 commit

**Comment by avraham-shmueli** [comment]
it takes a long time before that slide starts.
Also on slide 7 the text disappears
